//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace SOAPMessagingOnly.WebServiceClient.CustomerProcessingWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerProcessingSoap", Namespace="http://www.digitaldeposit.net/biztalk/samples")]
    public partial class CustomerProcessing : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductInfoByAccountNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerProcessing() {
            this.Url = global::SOAPMessagingOnly.WebServiceClient.Properties.Settings.Default.SOAPMessagingOnly_WebServiceClient_CustomerProcessingWebReference_CustomerProcessing;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductInfoCompletedEventHandler GetProductInfoCompleted;
        
        /// <remarks/>
        public event GetProductInfoByAccountNumberCompletedEventHandler GetProductInfoByAccountNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.digitaldeposit.net/biztalk/samples/GetProductInfo", RequestNamespace="http://www.digitaldeposit.net/biztalk/samples", ResponseNamespace="http://www.digitaldeposit.net/biztalk/samples", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.digitaldeposit.net/biztalk/samples/Product")]
        public GetProductInfoResult GetProductInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.digitaldeposit.net/biztalk/samples/Customer")] CustomerInfo CustomerInfo) {
            object[] results = this.Invoke("GetProductInfo", new object[] {
                        CustomerInfo});
            return ((GetProductInfoResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductInfoAsync(CustomerInfo CustomerInfo) {
            this.GetProductInfoAsync(CustomerInfo, null);
        }
        
        /// <remarks/>
        public void GetProductInfoAsync(CustomerInfo CustomerInfo, object userState) {
            if ((this.GetProductInfoOperationCompleted == null)) {
                this.GetProductInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductInfoOperationCompleted);
            }
            this.InvokeAsync("GetProductInfo", new object[] {
                        CustomerInfo}, this.GetProductInfoOperationCompleted, userState);
        }
        
        private void OnGetProductInfoOperationCompleted(object arg) {
            if ((this.GetProductInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductInfoCompleted(this, new GetProductInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.digitaldeposit.net/biztalk/samples/GetProductInfoByAccountNumber", RequestNamespace="http://www.digitaldeposit.net/biztalk/samples", ResponseNamespace="http://www.digitaldeposit.net/biztalk/samples", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.digitaldeposit.net/biztalk/samples/Product")]
        public GetProductInfoByAccountNumberResult GetProductInfoByAccountNumber([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.digitaldeposit.net/biztalk/samples/Customer")] customer customer, int accountNumber) {
            object[] results = this.Invoke("GetProductInfoByAccountNumber", new object[] {
                        customer,
                        accountNumber});
            return ((GetProductInfoByAccountNumberResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductInfoByAccountNumberAsync(customer customer, int accountNumber) {
            this.GetProductInfoByAccountNumberAsync(customer, accountNumber, null);
        }
        
        /// <remarks/>
        public void GetProductInfoByAccountNumberAsync(customer customer, int accountNumber, object userState) {
            if ((this.GetProductInfoByAccountNumberOperationCompleted == null)) {
                this.GetProductInfoByAccountNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductInfoByAccountNumberOperationCompleted);
            }
            this.InvokeAsync("GetProductInfoByAccountNumber", new object[] {
                        customer,
                        accountNumber}, this.GetProductInfoByAccountNumberOperationCompleted, userState);
        }
        
        private void OnGetProductInfoByAccountNumberOperationCompleted(object arg) {
            if ((this.GetProductInfoByAccountNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductInfoByAccountNumberCompleted(this, new GetProductInfoByAccountNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CustomerInfo {
        
        private string customerIDField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetProductInfoResult {
        
        private string productIDField;
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class customer {
        
        private string customerIDField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetProductInfoByAccountNumberResult {
        
        private string productIDField;
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProductInfoCompletedEventHandler(object sender, GetProductInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductInfoResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductInfoResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProductInfoByAccountNumberCompletedEventHandler(object sender, GetProductInfoByAccountNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductInfoByAccountNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductInfoByAccountNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductInfoByAccountNumberResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductInfoByAccountNumberResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591